export const productsInStock = [
  {
    id: 1,
    name: "Телефон",
    price: 10000,
    quantity: 10,
    city: "Kyiv",
    districts: ["район 1", "район 2", "район 3"],
    image: "/src/images/about-img-1.jpeg",
  },
  {
    id: 2,
    name: "Ноутбук",
    price: 20000,
    quantity: 5,
    city: "Kyiv",
    districts: ["район 4", "район 5", "район 6"],
    image: "/src/images/about-img-2.jpeg",
  },
  {
    id: 3,
    name: "Телевизор",
    price: 30000,
    quantity: 2,
    city: "Kyiv",
    districts: ["район 7", "район 8"],
    image: "/src/images/about-img-1.jpeg",
  },
  {
    id: 13,
    name: "Телефон",
    price: 10000,
    quantity: 10,
    city: "Kyiv",
    districts: ["район 9", "район 10", "район 11"],
    image: "/src/images/about-img-2.jpeg",
  },
  {
    id: 4,
    name: "Телефон",
    price: 10000,
    quantity: 10,
    city: "Fastiv",
    districts: ["район 1", "район 2", "район 3"],
    image: "images/barbers-img-3.jpeg",
  },
  {
    id: 6,
    name: "Телевизор",
    price: 30000,
    quantity: 2,
    city: "Fastiv",
    districts: ["район 3", "район 4", "район 5"],
    image: "images/gallery-img-1-tab.jpeg",
  },
  {
    id: 7,
    name: "Телефон",
    price: 10000,
    quantity: 10,
    city: "Boryspil",
    districts: ["район 3", "район 4", "район 5"],
    image: "images/gallery-img-1.jpeg",
  },
  {
    id: 5,
    name: "Ноутбук",
    price: 20000,
    quantity: 5,
    city: "Boryspil",
    districts: ["район 1", "район 2", "район 3"],
    image: "images/gallery-img-2.jpeg",
  },
  {
    id: 8,
    name: "Ноутбук",
    price: 20000,
    quantity: 5,
    city: "Brovary",
    districts: ["район 1", "район 2", "район 3"],
    image: "images/gallery-img-3.jpeg",
  },
  {
    id: 9,
    name: "Телевизор",
    price: 30000,
    quantity: 2,
    city: "Brovary",
    districts: ["район 13", "район 4", "район 5"],
    image: "images/gallery-img-4.jpeg",
  },
  {
    id: 15,
    name: "Телевизор",
    price: 30000,
    quantity: 2,
    city: "Brovary",
    districts: ["район 11", "район 12", "район 9"],
    image: "images/hero-bg-mob.jpeg",
  },
  {
    id: 10,
    name: "Телефон",
    price: 10000,
    quantity: 10,
    city: "Motovylivka",
    districts: ["район 1", "район 2", "район 3"],
    image: "images/hero-bg-tab-2x.jpeg",
  },
  {
    id: 11,
    name: "Ноутбук",
    price: 20000,
    quantity: 5,
    city: "Motovylivka",
    districts: ["район 11", "район 12", "район 13"],
    image: "images/hero-bg-tab.jpeg",
  },
  {
    id: 12,
    name: "Телевизор",
    price: 30000,
    quantity: 2,
    city: "Motovylivka",
    districts: ["район 14", "район 8", "район 9"],
    image: "images/hero-bg.jpeg",
  },
  {
    id: 14,
    name: "Ноутбук",
    price: 20000,
    quantity: 5,
    city: "Motovylivka",
    districts: ["район 4", "район 5", "район 6"],
    image: "images/about-img-1.jpeg",
  },
];
